#!/bin/bash
# Assembles the GuessWho LinkedIn Chrome/Brave extension into dist/<flavor>/.
#
#   ./build.sh [debug|release|store|all]     (default: debug)
#
# The extension is NOT a separate copy of the code: parse-profile.js,
# content.js, popup.html, popup.js, and the icons are copied VERBATIM from the
# Safari extension (../GuessWhoLinkedIn/Resources) at build time, so the
# LinkedIn parser has exactly one source of truth. Only manifest.json,
# background.js (localhost transport instead of sendNativeMessage), and the
# generated config.js are Chrome-specific — they live in Sources/.
#
# Flavor wiring (wake scheme, display name, app listener port) is PARSED FROM
# THE XCCONFIGS (GuessWho-<Config>.xcconfig / GuessWhoLinkedIn-<Config>.xcconfig)
# rather than duplicated here, so the extension can never drift from the app —
# the same "byte-identical identifiers" rule the Safari extension follows.
#
# Flavors:
#   debug    dist/debug/    — pinned dev key (stable ID), Debug port + scheme.
#            Load unpacked in Brave/Chrome; talks to the DEBUG app only.
#   release  dist/release/  — pinned dev key, Release port + scheme. Load
#            unpacked to test against a Release/TestFlight app install.
#   store    dist/store/ + build/GuessWhoChrome-<version>.zip — Release wiring,
#            NO "key" (the Chrome Web Store manages the published key/ID; a
#            manifest "key" in an uploaded package is rejected). Upload the zip
#            in the CWS developer dashboard. See README.md.
set -euo pipefail
cd "$(dirname "$0")"

SAFARI_RESOURCES="../GuessWhoLinkedIn/Resources"
CONFIG_DIR="../Config"
SHARED_FILES=(parse-profile.js content.js popup.html popup.js)

# Last assignment of an xcconfig variable in a file (after #include expansion
# the per-config file wins, and these vars only appear in per-config files).
xcconfig_value() { # <file> <VAR>
  sed -n "s/^ *$2 *= *//p" "$1" | tail -1
}

VERSION="$(xcconfig_value "$CONFIG_DIR/SharedVersion.xcconfig" MARKETING_VERSION)"
[ -n "$VERSION" ] || { echo "error: MARKETING_VERSION not found in SharedVersion.xcconfig" >&2; exit 1; }

# The extension ID Chrome derives from a manifest "key": first 16 bytes of
# SHA-256 over the decoded key, hex-mapped 0-9a-f → a-p. Printed so the ID
# shown in brave://extensions can be checked against the app's allowlist
# (GUESSWHO_CHROME_EXTENSION_IDS in GuessWho-<Config>.xcconfig).
extension_id() { # <base64-key>
  printf '%s' "$1" | base64 -d | shasum -a 256 | cut -c1-32 | tr '0123456789abcdef' 'abcdefghijklmnop'
}

build_flavor() { # <flavor>
  local flavor="$1" xcconfig_name key_file
  case "$flavor" in
    debug)         xcconfig_name="Debug";   key_file="keys/debug.pub" ;;
    release)       xcconfig_name="Release"; key_file="keys/release.pub" ;;
    store)         xcconfig_name="Release"; key_file="" ;;
    *) echo "error: unknown flavor '$flavor' (want debug|release|store|all)" >&2; exit 1 ;;
  esac

  local app_xcconfig="$CONFIG_DIR/GuessWho-$xcconfig_name.xcconfig"
  local ext_xcconfig="$CONFIG_DIR/GuessWhoLinkedIn-$xcconfig_name.xcconfig"
  local name scheme port
  name="$(xcconfig_value "$ext_xcconfig" GUESSWHO_EXTENSION_DISPLAY_NAME)"
  scheme="$(xcconfig_value "$app_xcconfig" GUESSWHO_LINKEDIN_URL_SCHEME)"
  port="$(xcconfig_value "$app_xcconfig" GUESSWHO_CHROME_HANDOFF_PORT)"
  [ -n "$name" ] && [ -n "$scheme" ] && [ -n "$port" ] || {
    echo "error: missing GUESSWHO_EXTENSION_DISPLAY_NAME / GUESSWHO_LINKEDIN_URL_SCHEME / GUESSWHO_CHROME_HANDOFF_PORT in $xcconfig_name xcconfigs" >&2
    exit 1
  }

  local out="dist/$flavor"
  rm -rf "$out"
  mkdir -p "$out"

  local f
  for f in "${SHARED_FILES[@]}"; do
    cp "$SAFARI_RESOURCES/$f" "$out/"
  done
  cp "$SAFARI_RESOURCES"/icon-*.png "$out/"
  cp Sources/background.js "$out/"

  # manifest.json from the template. sed keeps this dependency-free; the name
  # never contains sed metacharacters (letters/spaces only).
  if [ -n "$key_file" ]; then
    local key
    key="$(cat "$key_file")"
    sed -e "s|__DISPLAY_NAME__|$name|g" \
        -e "s|__VERSION__|$VERSION|g" \
        -e "s|__KEY__|$key|g" \
        Sources/manifest.template.json > "$out/manifest.json"
    echo "$flavor: $out (name=\"$name\", port=$port, scheme=$scheme, id=$(extension_id "$key"))"
  else
    sed -e "s|__DISPLAY_NAME__|$name|g" \
        -e "s|__VERSION__|$VERSION|g" \
        -e '/"key": "__KEY__",/d' \
        Sources/manifest.template.json > "$out/manifest.json"
    echo "$flavor: $out (name=\"$name\", port=$port, scheme=$scheme, id=assigned by the Web Store)"
  fi

  cat > "$out/config.js" <<EOF
// GENERATED by build.sh — do not edit. Per-flavor wiring for background.js,
// parsed from the $xcconfig_name xcconfigs so it can't drift from the app.
export const CONFIG = {
  flavor: "$flavor",
  port: $port,
  wakeScheme: "$scheme",
};
EOF

  if [ "$flavor" = "store" ]; then
    mkdir -p build
    local zip_path="build/GuessWhoChrome-$VERSION.zip"
    rm -f "$zip_path"
    (cd "$out" && zip -qr "../../$zip_path" . -x "*.DS_Store")
    echo "store zip: $zip_path"
  fi
}

FLAVOR="${1:-debug}"
if [ "$FLAVOR" = "all" ]; then
  build_flavor debug
  build_flavor release
  build_flavor store
else
  build_flavor "$FLAVOR"
fi
