// AUTO-GENERATED by the guesswho-cli.xcodeproj Generate phase from the CLI App Group build setting - do not edit.
enum BuildSettings {
    static let GUESSWHO_CLI_APP_GROUP = "T68Z94627S.com.milestonemade.guesswho.cli"
}
